global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'nginx-service'
    static_configs:
      - targets: ['localhost:80']
rule_files:
  - "rules.yml"


