groups:
- name: service-alerts
  rules:
  - alert: NginxDown
    expr: up{job="nginx-service"} == 0
    for: 15s
    labels:
      severity: critical
    annotations:
      description: "NGINX service is down."

  - alert: HighCPU
    expr: node_cpu_seconds_total{mode="idle"} < 0.1
    for: 30s
    labels:
      severity: warning
    annotations:
      description: "CPU usage is above 90%."

